### ISSUE TITLE
zeta is not used

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#10]
https://github.com/kassonlab/covid19-epi/blob/3dab2299c1ec68e5ce945486edac4ccf9b23b658/covid19.c#L749

Intentionally or?

**Comment by jasminegardner** [comment]
The use of zeta has been moved out of this function.  The effect of zeta is addressed in the main function.

**Comment by RogerJL** [comment]
Intentionally dead code should be removed
