### ISSUE TITLE
Why multiply transmission factor with 8.4?

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#11]
/* Modified factors to account for difference between population in Southeast Asia from Ferguson Model and Swedish population. This adjustment maintains 1/3 transmission in community, 1/3 transmission in household, and 1/3 transmission in workplace. 
	Overall population is 8.4X smaller in Sweden, attributed as a 8.4X increase in community transmission factor.
	Household size is approximately 2X smaller in Sweden, 2 vs. 4, attributed as a 2X increase in household transmission factor.
	R0 Scaling factor used to set approximate doubling time.  R0_scale=2.2 attributes to a doubling time of approximately 3 days while R0_scale=1.8 attributes to a doubling time of approximately 5 days.  
*/ 
https://github.com/kassonlab/covid19-epi/blob/3dab2299c1ec68e5ce945486edac4ccf9b23b658/covid19.c#L29

used as

	double betac=0.103 ; // Scaled from betac=0.075 in influenza pandemic with R0=1.6, COVID-19 R0=2.2 (Ferguson 2020)

	fd=1/(1+pow((d/4), 3)); //kernel density function as parameterized for GB.
	return (betac_scale*betac*kappa*fd*(1+severe*(omega-1)));

shouldn't betac_scale rather be 1/8.4 if anything? "8.4X smaller"

Do Ferguson really scale this too in his calculations depending on population size?
Same for the 2x factor for household size (can't imagine why you need an extra factor if simulation of houshold tranmissions are correct)

**Comment by jasminegardner** [comment]
Yes, read the literature.  Infection is intentionally allocated to 1/3 occurring in household, 1/3 occurring in community transmission, and 1/3 occurring in schools/workplaces.  These factors must scale with population.

**Comment by RogerJL** [comment]
Sorry, but that does not make sense to me.

Do you really say that this is an INPUT to the model rather than an OUTPUT?
"Infection is intentionally allocated to 1/3 occurring in household, 1/3 occurring in community transmission, and 1/3 occurring in schools/workplaces."

Lets assume a country of single households only, would you still assume 1/3 to occur in households and scale that factor up twice more?

Or a country with only 10 persons, living by them selves in one house of their own 20 km apart.
Would you scale up 8400000 times?

That assumption about where infections happens can only be valid in one specific country, but simulating each person that should be the OUTPUT of the simulation - how many were infected and where...

**Comment by jasminegardner** [comment]
Then read the literature.  This isn't a forum to help you understand the model.

**Comment by RogerJL** [comment]
Note: thread has been edited, the other participants comments are removed - makes my comments to loose context.
