### ISSUE TITLE
Missing comment creates confusion why houshold index is used with location arrays

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#13]
https://github.com/kassonlab/covid19-epi/blob/3dab2299c1ec68e5ce945486edac4ccf9b23b658/covid19.c#L130

This first loop is missing a comment, something along the line of
/* Place one household with one adult at each location */
(first loop HH_count is thus both counting households and locations, making code like
https://github.com/kassonlab/covid19-epi/blob/3dab2299c1ec68e5ce945486edac4ccf9b23b658/covid19.c#L134
make sense)

**Comment by jasminegardner** [comment]
Once again, you not understanding the code does not equate to an issue.
