### ISSUE TITLE
Builds but crashes with a segmentation fault

### ISSUE THREAD

**Issue by algal** [kassonlab/covid19-epi#14]
Builds correctly but then crashes when run on a stock Amazon Ubuntu 18.04 Deep Learning image AMI as of 2020-05-13T1412.

A machine instantiated from this image is pre-installed with cmake 13.3.3, CUDA 10.0, and nvcc. It has the GNU compiler, not the Intel compiler.

I'm not sure if this is intended to be a supported configuration, but the README suggests it is, and it compiles without errors, so I thought I would report this.

I tried this on the following exactly AWS AMI ID and instance type:

```
aws_ami_id=ami-09517d3f1a9a1cd9a
aws_instance_type=g3s.xlarge

```

**Comment by peterkasson** [comment]
Thanks.  Could you give the command line arguments you ran with and stdout/stderr?
Also just checking--the GPUs in this image are M60?

**Comment by peterkasson** [comment]
We identified and corrected segfaults related to default comment arguments in May.
I think this should be fixed now.  Please correct me if you find it is not.
