### ISSUE TITLE
Dead code or loop missing

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#15]
https://github.com/kassonlab/covid19-epi/blob/7c288c213887d2247265e5480fafe844dbe0558c/covid19.c#L2174

Usually 'i' loops over population, here the loop is missing => 'i' reuses old value
most likely from last loop, i.e i=population
This is likely to result in an access out of range 0..population-1

**Comment by peterkasson** [comment]
Thanks--issue accepted.  We'll take a look.

**Comment by peterkasson** [comment]
PS both apply:  this code is currently unused, but there is a loop missing.  Arguably, dead code should be removed, but in the meantime we will fix.

**Comment by peterkasson** [comment]
Fixed for us; marking closed.  Again, if you find an issue with the fix, please comment, and we'll reopen.
