### ISSUE TITLE
Unnecessary randomness when initializating?

### ISSUE THREAD

**Issue by RogerJL** [kassonlab/covid19-epi#9]
https://github.com/kassonlab/covid19-epi/blob/3dab2299c1ec68e5ce945486edac4ccf9b23b658/covid19.c#L379

There is probably existing data that has been used to calculate the percentages you use to put individuals in different classes, by doing so you could get vastly different starting states.
From all working to none working...

Why not a simple calculation without randomness?
 (count number in group) place in sub-groups using percentages
Then the randomness would move only to infection transfer

**Comment by jasminegardner** [comment]
No, it is absolutely necessary.  Individuals are allocated to locale sequentially, therefore everything afterwards must be random or we will have pockets of locales that are all unemployed and these will be biased towards less-dense locales.  With 10 million individuals, to obtain a random state where none are working would be very, very unlikely.  Similarly with a state where all are working.  Based on actual percentage of unemployed in the states simulated for our study (well over 1,000 runs), the randomness here is behaving as expected.

**Comment by peterkasson** [comment]
To do a non-random initialization, one would need data on the exact household (address and apartment number) as well as exact workplace group or school class for everyone in Sweden.  We judged that both a bit out of scope and potentially having privacy implications although much of these data are public in Sweden.
